### ISSUE TITLE
LastScene

### ISSUE THREAD

**Issue by SultanKh** [jce-il/se-class#22]
team main goal: testing the app on real users- validate the agility of all the functions and algorithms written.
validate the facebook/google login.
and the application is up to date and favorable solution for many users.

**Comment by dudiventura** [comment]
אתה מוסיף במקום הלא נכון

**Comment by moranlev** [comment]
אתם שולחים לי מיילים כל הזמן  ואני לא קשורה לזה. נא לא לשליח לי מיילים
בנושא זה יותר.
בתאריך 27 באפר 2015 20:14, "SultanKh" <notifications@github.com> כתב:
