### ISSUE TITLE
Open Ex links (pdf files) in new Tab

### ISSUE THREAD

**Issue by ItamarShDev** [jce-il/se-class#23]
i have s suggestion to the side bar.
in the links to PDF file (like exercises and such), use the following format to open them in a new tab, which will make students' life easier, and navigation more natural.

the format:
instead of using Markdown's " [ "name "] (" link ") " format 
use: < a href="http://link.to/pdf"  target="_blank ">link name< /a >

i fixed you TDD link to be in this format, you can check it out there

**Comment by robi-y** [comment]
I think it's a matter of taste http://ux.stackexchange.com/a/20097

**Comment by ItamarShDev** [comment]
I know, yet opening PDF file is somewhat like downloading a file. 
Also I was suggesting this, because I see people struggling with this

**Comment by robi-y** [comment]
The thing is that also all slides are currently in pdf (maybe I'll at least warn at this column header)
let's poll the class about it? @jce-il/students2015b

**Comment by portnoi** [comment]
Please remove me from the post list
